# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Publish NPM

on:
  workflow_dispatch:

  release:
    types:
      - created

env:
  NODE_VERSION: lts/*

jobs:
  publish-npm:
    if: github.repository_owner == 'njfamirm'

    name: Publish NPM
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: ⤵️ Checkout repository
        uses: actions/checkout@v4.1.1

      - name: 🏗 Setup nodejs
        uses: actions/setup-node@v4.0.0
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: https://registry.npmjs.org/
          cache: yarn

      - name: 🏗 Install dependencies
        run: yarn install --immutable

      - name: 🏗 Build Typescript
        run: yarn build:ts

      - name: 🏗 Run ESLint
        run: yarn lint:ts

      - name: 🚀 Publish
        run: yarn run publish --yes
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
